# Redis 嵌入式配置
port 6379
bind 127.0.0.1
timeout 300
tcp-keepalive 60

# 持久化
save 900 1
save 300 10
save 60 10000
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# 内存限制
maxmemory 256mb
maxmemory-policy allkeys-lru

# 日志
loglevel notice
logfile "./redis.log"

# 数据库数量
databases 16
